name: Unit tests of UH2SC by pytest on several platforms
on: [push]
jobs:  
  RunUH2SCpytest:
    strategy:
      matrix:
        # run all 3 major platforms  removed: macos-latest, ubuntu-latest 
        os: [windows-latest, macos-latest, ubuntu-latest]
        pyversion: ['3.10', '3.11', '3.12']
  
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        #with: 
        #  ref: develop 
      - name: Install Python3
        uses: actions/setup-python@v1
        with:
           python-version: ${{ matrix.pyversion }}
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install -e .[test]
      - name: run tests with pytest
        run: |
           pytest 
           #--doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
