name: Publish Python 🐍 uh2sc distribution 📦 to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi  # Optional: Define an environment for added security
      url: https://pypi.org/p/uh2sc/ # Replace with your package URL
    permissions:
      id-token: write # THIS IS MANDATORY for Trusted Publishing
      contents: read # Allow checkout to read repository contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build # or your preferred build system like setuptools_scm

      - name: Build package distributions
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # No need for username and password with trusted publishers

